name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/step-uv@7

      - name: Setup python
        uses: uv python install 3.14

      - name: Install dependencies
        uses: uv sync --locked
      
      - name: Run Lint
        uses: uv run ruff check .

  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --locked
        
      - name: Run Tests
        run: uv run pytest -v
  
  build:
    needs:
      - lint
      - test
    
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: echo "Build started!!"