name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --locked
      
      - name: Run Lint
        run: uv run ruff check .

  test: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Setup python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync --locked
        
      - name: Run Tests
        run: uv run pytest -v
  
  build:
    needs:
      - lint
      - test
    
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to Github Container Registry
        uses: docker/login-actions@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image 
        uses: docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .

      - name: Push Docker image
        uses: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      